- id: doi:10.64898/2026.05.13.724735
  image: images/publications/2026-aav-nrf2-gdf15.jpg

- id: doi:10.1101/2025.07.09.663952
  image: images/publications/2025-aav-nrf2-gene-therapy.jpg

- id: doi:10.1109/TIM.2025.3606015
  image: images/publications/2025-oct-octa-org.svg

- id: doi:10.1186/s12967-024-04877-6
  image: images/publications/2024-fucoidan-retinopathy.png

- id: doi:10.1016/j.redox.2018.02.022
  image: images/publications/2018-lmp10-retinopathy.jpg

- id: doi:10.1016/j.ymthe.2019.09.025
  image: images/publications/2020-beta5i-hypertensive-retinopathy.jpg

- id: doi:10.1016/j.redox.2022.102438
  image: images/publications/2022-cxcl1-cxcr2-retinopathy.jpg

- id: doi:10.3389/fphar.2023.1164333
  image: images/publications/2023-fucoidan-cardiac-remodeling.jpg

- id: doi:10.1016/j.lfs.2020.118795
  image: images/publications/2021-conbercept-retinopathy.jpg

- id: doi:10.1167/iovs.61.14.30
  image: images/publications/2020-immunosubunit-beta5i-neovascularization.jpg

- id: doi:10.1016/j.ajo.2024.04.021
  image: images/publications/2024-secondary-glaucoma-meta-analysis.jpg

- id: doi:10.3390/polym15010023
  image: images/publications/2022-apigenin-silk-fibroin.jpg

- id: doi:10.1186/s12935-021-01833-y
  image: images/publications/2021-fbxo-breast-cancer.png

- id: doi:10.1016/j.jare.2023.02.010
  image: images/publications/2024-cd11b-cardiac-remodeling.jpg

- id: doi:10.1016/j.biopha.2018.10.134
  image: images/publications/2019-taurine-pancreas.jpg

- id: doi:10.1161/HYPERTENSIONAHA.118.11813
  image: images/publications/2019-beta5i-atrial-fibrillation.svg

- id: doi:10.1161/HYPERTENSIONAHA.117.10390
  image: images/publications/2018-psmb10-atrial-fibrillation.svg

- id: doi:10.1161/HYPERTENSIONAHA.122.20328
  image: images/publications/2023-cd11b-hypertension.svg
